import firebase from "../firebase";

export default test("FireBase", async () => {
  const accestoken =
    "eyJhbGciOiJSUzI1NiIsImtpZCI6ImNmNWQ4ZTc0ZjNjNDg2ZWU1MDNkNWVlYzkzYTEwMWM2NGJhY2Y3ZGEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vaXRob3VzZS1mMzQ2ZiIsImF1ZCI6Iml0aG91c2UtZjM0NmYiLCJhdXRoX3RpbWUiOjE2NDU5NDQyMzcsInVzZXJfaWQiOiJjMUNRM01Jbk1OYXJ6VlFFcFFHVUxMdWdJd3ExIiwic3ViIjoiYzFDUTNNSW5NTmFyelZRRXBRR1VMTHVnSXdxMSIsImlhdCI6MTY0NTk0NDIzNywiZXhwIjoxNjQ1OTQ3ODM3LCJlbWFpbCI6ImRhY3Z1aXBzQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJkYWN2dWlwc0BnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.Qe729qtDYNf4taLQYf7v2cFLe-HkRaSuujQutB2rJcCdgqBXqHokHF1bppWCDGvZXVYsysJDwGzrO7cM3CWDZKnoDNtprP1RlkttoFsn0Q70CKai7BnqrT9C6JXxVh9Czs_NC6ed3fQVXXwr8_QUFNKJECsQShwwAzHciVRpwHZ3iLuDkPw90inDaW-dyORUty_YkL6be6XeobAFQ9ssggymXt_2tecBNHMe9yjItvyN5VElrkNQqks_vdqtcTxgIs31AE_oIjtrnh1zLMAZ740MVlrwCpMRMTY8vGha-8Gh_l5TQwC3j7tjEzUahbHkFifmjX3FPGeM4fU10P-g0A";
  const decodedToken = await firebase.auth().verifyIdToken(accestoken);
  console.log("DecodedToken", decodedToken);
});
