@startuml


package User{
map User{
    id =>string
    username=>string
    name=>string
    password=>string
    email=>string
    phone=>number
    address=>Address
    
    activated=>boolean
    address=>string
    created_at=>string
    updated_at=>string
    role=>Role 
}
object Role{
    admin
    user
    merchant
    membership
}
map Address{

    address=>string
    district=>string
    ward=>string
    city=>string
    street=>string
    house_number=>string
    created_at=>string
    updated_at=>string

}



}

package Product{
map SanPham{
    id =>string
    name=>string
    image=>string
    price=>number
    description=>string
    quantity=>number
    rating=>number
    category_id=>string
    created_at=>string
    updated_at=>string
}
map Topping{
    id =>string
    name=>string
    price=>number
    created_at=>string
    updated_at=>string
}
map Tag{

Hot=>string
New=>string
Sale=>number
lovely=>string
voucher=>string
}
}

package Login{
map Login{
    User=>User
    password=>string

}

map ForgottenPassword{

    email=>string
    username=>string
}
map Register{
    username=>string
    name=>string
    password=>string
    email=>string
    phone=>number
    address=>Address
    address=>string
    created_at=>string
    updated_at=>string
}
}
package Order{
map DonHang{
    id =>string
    name=>string
    price=>number
    description=>string
    product_id=>array
    user_id=>string
    created_at=>string
    updated_at=>string

}


}

User ==> DonHang
SanPham ==> DonHang
SanPham ==> Topping
SanPham ==> Tag
User ==> SanPham
User ==> Address
User ==> Role
Login==>User
ForgottenPassword==>User
Register==>User




@enduml